version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: short_bulletin_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/short_bulletin_db?currentSchema=public
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_DATASOURCE_INITIALIZATION_MODE: always
      SPRING_DATASOURCE_SCHEMA: classpath:db/migration/V1__init.sql
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  # Switch to 'update' after first run
      LLM_BASE_URL: http://host.docker.internal:12434/v1/chat/completions
      LLM_MODEL: ai/gemma3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: