server:
  port: 8080

spring:
  application:
    name: short-bulletin
  datasource:
    url: jdbc:postgresql://db:5432/short_bulletin_db?currentSchema=public
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    schema: classpath:db/migration/V1__init.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false
  #ai:
    #openai:
      #base-url: http://localhost:12434/engines
      #api-key: docker
      #chat:
        #options:
          #model: ai/gemma3:1B-Q4_K_M

llm:
  base-url: http://host.docker.internal:12434/v1/chat/completions
  model: ai/gemma3

jwt:
  secret: v8L7iLxJp6mQGhQ3ZfRjAyjZwHgMXiGHqMoY5KUwV88=
  expiration: 36000000  # 10 hours in milliseconds